lane :setup do
  sh "cp ./Config.Fabric.xcconfig ../StreetFighterV/Resources/Configs/Config.Fabric.xcconfig"
  ["FABRIC_API_KEY", "FABRIC_BUILD_SECRET"].each do |key|
    set_xcconfig_value(
      path: './StreetFighterV/Resources/Configs/Config.Fabric.xcconfig', 
      name: key, 
      value: ENV[key]
    )
  end

  ["Debug", "Release"].each do |configuration|
    sh "cp ./GoogleService-Info.plist ../StreetFighterV/Resources/GoogleService/GoogleService-Info.#{configuration}.plist"

    [
      "AD_UNIT_ID_FOR_BANNER_TEST",
      "AD_UNIT_ID_FOR_INTERSTITIAL_TEST",
      "CLIENT_ID",
      "REVERSED_CLIENT_ID",
      "API_KEY",
      "GCM_SENDER_ID",
      "PROJECT_ID",
      "STORAGE_BUCKET",
      "GOOGLE_APP_ID",
      "DATABASE_URL"
    ].each { |key|
      set_info_plist_value(
        path: "./StreetFighterV/Resources/GoogleService/GoogleService-Info.#{configuration}.plist", 
        key: key,
        value: ENV["#{configuration.upcase}_#{key}"], 
        output_file_name: "./StreetFighterV/Resources/GoogleService/GoogleService-Info.#{configuration}.plist"
      )
    }
  end

  xcodegen(spec: "./project.yml")
  cocoapods(verbose: true)
end