lane :setup do
  set_info_plist_value(
    path: "./fastlane/Info.plist", 
    key: "Fabric", 
    subkey: "APIKey", 
    value: ENV["FABRIC_API_KEY"], 
    output_file_name: "./StreetFighterV/Resources/Info.plist"
  )

  sh "cp ./GoogleService-Info.plist ../StreetFighterV/Resources/GoogleService-Info.plist"

  [
    "AD_UNIT_ID_FOR_BANNER_TEST",
    "AD_UNIT_ID_FOR_INTERSTITIAL_TEST",
    "CLIENT_ID",
    "REVERSED_CLIENT_ID",
    "API_KEY",
    "GCM_SENDER_ID",
    "PROJECT_ID",
    "STORAGE_BUCKET",
    "GOOGLE_APP_ID",
    "DATABASE_URL"
  ].each { |key|
    set_info_plist_value(
      path: "./StreetFighterV/Resources/GoogleService-Info.plist", 
      key: key,
      value: ENV[key], 
      output_file_name: "./StreetFighterV/Resources/GoogleService-Info.plist"
    )
  }

  sh "cp ./fabric.sh ../scripts/fabric.sh"
  sh "sed -i.bak -e 's/FABRIC_API_KEY/#{ENV["FABRIC_API_KEY"]}/g' ../scripts/fabric.sh"
  sh "sed -i.bak -e 's/FABRIC_BUILD_SECRET/#{ENV["FABRIC_BUILD_SECRET"]}/g' ../scripts/fabric.sh"
end